### ISSUE TITLE
[BE] JWT 및 소셜 로그인 인증서버 구축

### ISSUE THREAD

**Issue by jymaeng95** [dev-nbbang/backend-auth#1]
## **✏️ Feature 작업**
새로운 Feature에 대해 설명해주세요.

## **✅ TO-DO** 
- [x] JWT 관련 기능 구현
- [x] 회원 서비스의 소셜 로그인 구현
- [x] 추가 정보 회원 가입시 이벤트 스트리밍 확인

## **🚨 주의사항** 
✔️ 주의 사항
